#!/bin/sh

mc_show () { echo }}} $mc_cmd_magic_kli7kubr; }
mc_new  () { unset  mc_cmd_magic_kli7kubr; }
mc_run  () { $mc_cmd_magic_kli7kubr; }
mc_add  () { export  mc_cmd_magic_kli7kubr="$mc_cmd_magic_kli7kubr $*"; }



mc () {
    case x$1 in
        x.show)
            mc_show ;;
        x.new)
            mc_new ;;
        x.run)
            mc_run ;;
        x--help|x-h)
            mc_usage >&2 ;;
        x.)
            shift;  mc_add $*  ;;
        *)
            echo 'try [mc -h].' >&2  ;;
    esac
}

mc_usage () {
cat << EOF
[MYFUNCTIONS] --  MC -- Make Command

        Build a complex command with varied options from pieces.

USAGE
        mc            -- this help
        mc -h         -- this help
        mc --help     -- this help
        mc .new       -- clear the buffer
        mc .run       -- run the buffer
        mc .show      -- run the buffer
        mc .  ARGS    -- append args to the buffer


EXAMPLE
        The lines
            $ mc .new
            $ mc .  find
            $ mc .  -name foo
            $ mc .run
        effectuates
            $ find -name foo

EOF
}
