#!/bin/sh
mc () {
    case .$1 in
        .--new)
            unset mc_cmd_magic_kli7kubr
            ;;
        .--run)
            $mc_cmd_magic_kli7kubr
            ;;
        .--add)
            shift
            export mc_cmd_magic_kli7kubr="$mc_cmd_magic_kli7kubr $*"
            ;;
        .-h|--help.)
            mc_usage
            ;;
    esac
}

mc_usage () {
cat << EOF
[MYFUNCTIONS] --  MC -- Make Command

        Build a complex command with varied options from pieces.

USAGE
        mc --new         -- clear the buffer
        mc --add ARGS    -- append args to the buffer
        mc --run         -- run the buffer

EXAMPLE
        The lines
            $ mc --new
            $ mc --add  find
            $ mc --add  -name foo
            $ mc --run
        effecuates
            $ find -name foo

EOF
}
